name: apiname
version: 1.0.0
description: ''
main: "./src/index.js"
scripts:
  start: pm2 start ecosystem.yaml --env development --only POLICY-API --update-env
  stop: pm2 delete ecosystem.yaml --env development --only POLICY-API
  devmon: nodemon --exec node -r esm ./src/index.js environment=localhost
  test: 'npm config set NODE_ENV=test &&  jest --verbose --coverage --maxWorkers=10
    --detectOpenHandles  --forceExit '
jest:
  testEnvironment: node
  coveragePathIgnorePatterns:
  - "/node_modules/"
  - "/src/test/"
  testResultsProcessor: jest-sonar-reporter
jestSonar:
  reportPath: coverage
  reportFile: test-reporter.xml
  indent: 4
keywords: []
author: ''
license: ISC
dependencies:
  "@graphql-tools/mock": "^8.5.1"
  child_process: "^1.0.2"
  esm: "^3.2.25"
  express: "^4.18.1"
  gql-generator: "^1.0.17"
  nodemon: "^2.0.19"
  pm2: "^5.2.0"
  pm2-logrotate: "^2.7.0"
  spectaql: "^1.5.4"
  tx2: "^1.0.5"
  subgraph-tools: file:packages/subgraph-tools-version.tgz
devDependencies:
  "@types/node": 12.12.14
  jest: "^27.5.1"
  jest-environment-node: "^26.1.0"
  jest-sonar-reporter: "^2.0.0"
  node-fetch: 2.6.6
  sonarqube-scanner: "^2.8.1"
  "@apollo/subgraph": "^2.0.5"
  "@graphql-tools/utils": "^8.5.1"
  apollo-server-core: "^3.10.0"
  apollo-server-errors: "^3.3.1"
  apollo-server-express: "^3.10.2"
  body-parser: "^1.20.0"
  cors: "^2.8.5"
  express-rate-limit: "^6.6.0"
  graphql: "^16.5.0"
  graphql-date: "^1.0.3"
  graphql-relay: "^0.7.0"
  graphql-voyager: "^1.0.0-rc.31"
  join-monster: "^3.1.1"
  join-monster-graphql-tools-adapter: "^0.1.1"
  js-yaml: "^4.1.0"
  minify-query-string: "^1.0.0"
  mssql: "^8.1.1"
  ssl-root-cas: "^1.3.1"
  xss-clean: "^0.1.1"
  yamljs: 0.3.0
